"""
Trading Strategies for Polymarket
Implements four core strategies that are combined in an ensemble:
1. Mispricing Hunter: Exploits divergence between model forecast and market price
2. Momentum Follower: Follows strong directional price trends
3. Arbitrage Scanner: Captures NegRisk and cross-market arbitrage
4. Whale Follower: Copies smart money / whale wallet positions
"""
import logging
import numpy as np
from typing import Any, Dict, List, Optional, Tuple
from dataclasses import dataclass, field
from enum import Enum

logger = logging.getLogger(__name__)


class TradeAction(Enum):
    BUY_YES = "BUY_YES"
    BUY_NO = "BUY_NO"
    SKIP = "SKIP"


@dataclass
class TradeSignal:
    """A trading signal generated by a strategy."""
    strategy: str
    market_id: str
    market_title: str
    action: TradeAction
    edge: float           # Estimated edge (0 to 1)
    confidence: float     # Signal confidence (0 to 1)
    suggested_price: float  # Price at which to enter
    reasoning: str
    metadata: Dict[str, Any] = field(default_factory=dict)


class KellyCriterion:
    """Kelly Criterion position sizing for prediction markets."""

    @staticmethod
    def calculate(
        p_win: float,
        b_odds: float,
        kelly_fraction: float = 0.25,
        max_fraction: float = 0.05,
    ) -> float:
        """
        Calculate Kelly fraction for a binary bet.

        Args:
            p_win: Probability of winning (model estimate)
            b_odds: Net odds (payout per unit bet, = 1/price - 1 for YES)
            kelly_fraction: Fractional Kelly multiplier (0.25 = quarter Kelly)
            max_fraction: Maximum allowed fraction of bankroll

        Returns:
            Fraction of bankroll to bet (0 to max_fraction)
        """
        if p_win <= 0 or b_odds <= 0:
            return 0.0
        q_win = 1.0 - p_win
        kelly = (b_odds * p_win - q_win) / b_odds
        kelly = max(0.0, kelly)  # Never bet negative Kelly
        fractional_kelly = kelly * kelly_fraction
        return min(fractional_kelly, max_fraction)


class MispricingHunterStrategy:
    """
    Mispricing Hunter Strategy
    Identifies markets where the Kronos model forecast diverges significantly
    from the current market price, indicating a potential mispricing.
    """

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.risk_cfg = config.get("risk", {})
        self.min_edge = self.risk_cfg.get("min_edge_threshold", 0.03)
        self.min_confidence = self.risk_cfg.get("min_confidence", 0.60)
        self.kelly_fraction = self.risk_cfg.get("kelly_fraction", 0.25)
        self.max_position = self.risk_cfg.get("max_bankroll_per_trade", 0.05)

    def evaluate(
        self,
        market: Dict[str, Any],
        forecast: Dict[str, Any],
        risk_assessment: Dict[str, Any],
    ) -> Optional[TradeSignal]:
        """Evaluate a market for mispricing opportunities."""
        current_price = forecast.get("current_price", 0.5)
        predicted_price = forecast.get("predicted_price", 0.5)
        confidence = forecast.get("confidence", 0.0)

        if confidence < self.min_confidence:
            return None

        # Risk grade filter
        grade = risk_assessment.get("overall_grade", "F")
        if grade in ("D", "F"):
            return None

        # Calculate edge for YES
        edge_yes = predicted_price - current_price
        # Calculate edge for NO
        edge_no = (1.0 - predicted_price) - (1.0 - current_price)

        best_edge = max(abs(edge_yes), abs(edge_no))
        if best_edge < self.min_edge:
            return None

        if abs(edge_yes) >= abs(edge_no):
            action = TradeAction.BUY_YES if edge_yes > 0 else TradeAction.BUY_NO
            edge = edge_yes if edge_yes > 0 else -edge_yes
            entry_price = current_price if action == TradeAction.BUY_YES else 1.0 - current_price
        else:
            action = TradeAction.BUY_NO if edge_no > 0 else TradeAction.BUY_YES
            edge = edge_no if edge_no > 0 else -edge_no
            entry_price = 1.0 - current_price if action == TradeAction.BUY_NO else current_price

        # Kelly sizing
        b_odds = (1.0 / entry_price) - 1.0 if entry_price > 0 else 0
        p_win = predicted_price if action == TradeAction.BUY_YES else 1.0 - predicted_price
        kelly_size = KellyCriterion.calculate(p_win, b_odds, self.kelly_fraction, self.max_position)

        if kelly_size <= 0:
            return None

        return TradeSignal(
            strategy="mispricing_hunter",
            market_id=market.get("id", ""),
            market_title=market.get("question", "")[:80],
            action=action,
            edge=edge,
            confidence=confidence,
            suggested_price=entry_price,
            reasoning=f"Model predicts {predicted_price:.2%} vs market {current_price:.2%}, edge={edge:.2%}",
            metadata={
                "kelly_size": kelly_size,
                "predicted_price": predicted_price,
                "current_price": current_price,
                "model": forecast.get("model", "unknown"),
            },
        )


class MomentumFollowerStrategy:
    """
    Momentum Follower Strategy
    Follows strong directional price trends identified by polyterm signals
    and confirmed by Kronos forecasts.
    """

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.risk_cfg = config.get("risk", {})
        self.min_confidence = self.risk_cfg.get("min_confidence", 0.60)
        self.kelly_fraction = self.risk_cfg.get("kelly_fraction", 0.25) * 0.8  # More conservative
        self.max_position = self.risk_cfg.get("max_bankroll_per_trade", 0.05) * 0.8

    def evaluate(
        self,
        market: Dict[str, Any],
        forecast: Dict[str, Any],
        signals: Optional[Dict[str, Any]],
        risk_assessment: Dict[str, Any],
    ) -> Optional[TradeSignal]:
        """Evaluate a market for momentum opportunities."""
        if signals is None:
            return None

        polyterm_direction = signals.get("direction", "neutral")
        polyterm_confidence = signals.get("confidence", 0.0)
        forecast_direction = forecast.get("direction", "neutral")
        forecast_confidence = forecast.get("confidence", 0.0)

        # Require both signals to agree
        if polyterm_direction != forecast_direction:
            return None
        if polyterm_direction == "neutral":
            return None

        combined_confidence = (polyterm_confidence + forecast_confidence) / 2.0
        if combined_confidence < self.min_confidence:
            return None

        # Risk grade filter
        grade = risk_assessment.get("overall_grade", "F")
        if grade in ("D", "F"):
            return None

        current_price = forecast.get("current_price", 0.5)
        action = TradeAction.BUY_YES if polyterm_direction == "bullish" else TradeAction.BUY_NO
        entry_price = current_price if action == TradeAction.BUY_YES else 1.0 - current_price

        # Edge estimate from momentum
        prob_change = abs(signals.get("probability_change", 0)) / 100.0
        edge = min(prob_change, 0.15)

        b_odds = (1.0 / entry_price) - 1.0 if entry_price > 0 else 0
        p_win = current_price + edge if action == TradeAction.BUY_YES else (1.0 - current_price) + edge
        p_win = min(p_win, 0.95)
        kelly_size = KellyCriterion.calculate(p_win, b_odds, self.kelly_fraction, self.max_position)

        if kelly_size <= 0:
            return None

        bullish_count = signals.get("signal_summary", {}).get("bullish", 0)
        bearish_count = signals.get("signal_summary", {}).get("bearish", 0)

        return TradeSignal(
            strategy="momentum_follower",
            market_id=market.get("id", ""),
            market_title=market.get("question", "")[:80],
            action=action,
            edge=edge,
            confidence=combined_confidence,
            suggested_price=entry_price,
            reasoning=f"Momentum {polyterm_direction}: {bullish_count}B/{bearish_count}B signals, conf={combined_confidence:.0%}",
            metadata={
                "kelly_size": kelly_size,
                "polyterm_direction": polyterm_direction,
                "forecast_direction": forecast_direction,
                "signal_summary": signals.get("signal_summary", {}),
            },
        )


class ArbitrageScannerStrategy:
    """
    Arbitrage Scanner Strategy
    Detects NegRisk and cross-market arbitrage opportunities where
    YES + NO prices deviate from 1.0 by more than transaction costs.
    """

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.risk_cfg = config.get("risk", {})
        self.min_spread = 0.025  # Minimum 2.5% arbitrage spread
        self.max_position = self.risk_cfg.get("max_bankroll_per_trade", 0.05)

    def evaluate_from_arb_data(
        self, arb_opportunity: Dict[str, Any]
    ) -> Optional[TradeSignal]:
        """Evaluate an arbitrage opportunity from polyterm's scanner."""
        spread = float(arb_opportunity.get("spread", 0))
        if spread < self.min_spread:
            return None

        market_id = arb_opportunity.get("market_id", "")
        market_title = arb_opportunity.get("title", "")
        yes_price = float(arb_opportunity.get("yes_price", 0.5))
        no_price = float(arb_opportunity.get("no_price", 0.5))

        # YES + NO < 1.0 means both can be bought for guaranteed profit
        total = yes_price + no_price
        if total < 1.0 - self.min_spread:
            action = TradeAction.BUY_YES  # Buy both (simplified: buy YES)
            edge = (1.0 - total) / 2.0
        else:
            return None

        return TradeSignal(
            strategy="arbitrage_scanner",
            market_id=market_id,
            market_title=market_title[:80],
            action=action,
            edge=edge,
            confidence=0.85,  # Arbitrage is high confidence
            suggested_price=yes_price,
            reasoning=f"Arbitrage: YES({yes_price:.3f})+NO({no_price:.3f})={total:.3f}<1.0, spread={spread:.3f}",
            metadata={
                "yes_price": yes_price,
                "no_price": no_price,
                "total": total,
                "kelly_size": self.max_position * 0.5,  # Conservative for arb
            },
        )


class WhaleFollowerStrategy:
    """
    Whale Follower Strategy
    Copies positions taken by wallets identified as 'smart money'
    based on their historical win rate and trade size.
    """

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.risk_cfg = config.get("risk", {})
        self.min_confidence = 0.65
        self.max_position = self.risk_cfg.get("max_bankroll_per_trade", 0.05) * 0.6

    def evaluate(
        self,
        market: Dict[str, Any],
        whale_activity: Optional[Dict[str, Any]],
        risk_assessment: Dict[str, Any],
    ) -> Optional[TradeSignal]:
        """Evaluate a market based on whale activity."""
        if whale_activity is None:
            return None

        smart_money_direction = whale_activity.get("smart_money_direction")
        smart_money_confidence = float(whale_activity.get("confidence", 0))
        whale_net_position = float(whale_activity.get("whale_net_position", 0))

        if smart_money_direction is None or smart_money_confidence < self.min_confidence:
            return None

        # Risk grade filter
        grade = risk_assessment.get("overall_grade", "F")
        if grade in ("D", "F"):
            return None

        current_price = float(market.get("lastTradePrice", 0.5) or 0.5)
        action = TradeAction.BUY_YES if smart_money_direction == "bullish" else TradeAction.BUY_NO
        entry_price = current_price if action == TradeAction.BUY_YES else 1.0 - current_price

        edge = min(abs(whale_net_position) * 0.1, 0.08)

        return TradeSignal(
            strategy="whale_follower",
            market_id=market.get("id", ""),
            market_title=market.get("question", "")[:80],
            action=action,
            edge=edge,
            confidence=smart_money_confidence,
            suggested_price=entry_price,
            reasoning=f"Smart money {smart_money_direction}: net_pos={whale_net_position:.0f}, conf={smart_money_confidence:.0%}",
            metadata={
                "kelly_size": self.max_position,
                "whale_net_position": whale_net_position,
                "smart_money_direction": smart_money_direction,
            },
        )


class EnsembleStrategy:
    """
    Ensemble Strategy
    Combines signals from all four strategies using configurable weights.
    Produces a final trade decision with aggregated confidence and position size.
    """

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        strategy_cfg = config.get("strategy", {})
        self.weights = strategy_cfg.get("ensemble_weights", {
            "mispricing_hunter": 0.35,
            "momentum_follower": 0.25,
            "arbitrage_scanner": 0.20,
            "whale_follower": 0.20,
        })
        self.risk_cfg = config.get("risk", {})
        self.min_edge = self.risk_cfg.get("min_edge_threshold", 0.03)
        self.min_confidence = self.risk_cfg.get("min_confidence", 0.60)

    def combine(self, signals: List[TradeSignal]) -> Optional[TradeSignal]:
        """
        Combine multiple strategy signals into a single ensemble decision.
        Uses weighted voting with edge and confidence as vote weights.
        """
        if not signals:
            return None

        # Weighted vote
        yes_score = 0.0
        no_score = 0.0
        skip_score = 0.0
        total_weight = 0.0
        weighted_edge = 0.0
        weighted_confidence = 0.0
        kelly_sizes = []

        for sig in signals:
            w = self.weights.get(sig.strategy, 0.25)
            vote_weight = w * sig.confidence * (1.0 + sig.edge)
            total_weight += vote_weight

            if sig.action == TradeAction.BUY_YES:
                yes_score += vote_weight
            elif sig.action == TradeAction.BUY_NO:
                no_score += vote_weight
            else:
                skip_score += vote_weight

            weighted_edge += sig.edge * vote_weight
            weighted_confidence += sig.confidence * vote_weight
            if "kelly_size" in sig.metadata:
                kelly_sizes.append(sig.metadata["kelly_size"] * w)

        if total_weight == 0:
            return None

        avg_edge = weighted_edge / total_weight
        avg_confidence = weighted_confidence / total_weight

        if avg_edge < self.min_edge or avg_confidence < self.min_confidence:
            return None

        # Determine final action
        max_score = max(yes_score, no_score, skip_score)
        if max_score == skip_score or (yes_score < 0.4 * total_weight and no_score < 0.4 * total_weight):
            return None

        final_action = TradeAction.BUY_YES if yes_score >= no_score else TradeAction.BUY_NO

        # Aggregate Kelly size
        avg_kelly = sum(kelly_sizes) / len(kelly_sizes) if kelly_sizes else 0.02
        # Scale by consensus strength
        consensus_strength = max(yes_score, no_score) / total_weight
        final_kelly = avg_kelly * consensus_strength

        # Use first signal's market info
        ref_signal = signals[0]
        strategy_names = [s.strategy for s in signals]
        reasoning_parts = [f"{s.strategy}({s.action.value})" for s in signals]

        return TradeSignal(
            strategy="ensemble",
            market_id=ref_signal.market_id,
            market_title=ref_signal.market_title,
            action=final_action,
            edge=avg_edge,
            confidence=avg_confidence,
            suggested_price=ref_signal.suggested_price,
            reasoning=f"Ensemble [{', '.join(reasoning_parts)}] consensus={consensus_strength:.0%}",
            metadata={
                "kelly_size": final_kelly,
                "yes_score": yes_score,
                "no_score": no_score,
                "consensus_strength": consensus_strength,
                "contributing_strategies": strategy_names,
            },
        )
